#!/usr/bin/env python
"""Execute the tests for the roi_intersect program.

The golden test outputs are generated by the script generate_outputs.sh.

You have to give the root paths to the source and the binaries as arguments to
the program.  These are the paths to the directory that contains the 'projects'
directory.

Usage:  run_tests.py SOURCE_ROOT_PATH BINARY_ROOT_PATH
"""
import logging
import os.path
import sys

# Automagically add util/py_lib to PYTHONPATH environment variable.
path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..',
                                    '..', '..', 'util', 'py_lib'))
sys.path.insert(0, path)

import seqan.app_tests as app_tests

def main(source_base, binary_base):
    """Main entry point of the script."""

    print 'Executing test for roi_intersect'
    print '================================'
    print
    
    ph = app_tests.TestPathHelper(
        source_base, binary_base,
        'sandbox/jagla/apps/roi_intersect/tests')  # tests dir

    # ============================================================
    # Auto-detect the binary path.
    # ============================================================

    path_to_program = app_tests.autolocateBinary(
      binary_base, 'sandbox/jagla/apps/roi_intersect', 'roi_intersect')

    # ============================================================
    # Built TestConf list.
    # ============================================================

    # Build list with TestConf objects, analoguely to how the output
    # was generated in generate_outputs.sh.
    conf_list = []

    # We prepare a list of transforms to apply to the output files.  This is
    # used to strip the input/output paths from the programs' output to
    # make it more canonical and host independent.
    ph.outFile('-')  # To ensure that the out path is set.
    transforms = [
        app_tests.ReplaceTransform(os.path.join(ph.source_base_path, 'sandbox/jagla/apps/roi_intersect/tests') + os.sep, '', right=True),
        app_tests.ReplaceTransform(ph.temp_dir + os.sep, '', right=True),
        ]

    # ------------------------------------------------------------
    # Intersect with BED or GFF/GTF in BED style.
    # ------------------------------------------------------------

    for mode in ['projection', 'union', 'difference', 'intersection']:
        for fmt in ['bed', 'gff', 'gtf']:
            for ss_flag, ss_name in [('-ss', '_ss'), ('', '')]:
                conf = app_tests.TestConf(
                    program=path_to_program,
                    redir_stderr=ph.outFile('out_small_%s_m%s%s.stderr' % (fmt, mode, ss_name)),
                    redir_stdout=ph.outFile('out_small_%s_m%s%s.stdout' % (fmt, mode, ss_name)),
                    args=['-m', mode, ss_flag,
                          '-ir', ph.inFile('small.roi'),
                          '-if', ph.inFile('small.%s' % fmt),
                          '-or', ph.outFile('out_small_%s_m%s%s.roi' % (fmt, mode, ss_name))],
                    to_diff=[(ph.inFile('out_small_%s_m%s%s.stderr' % (fmt, mode, ss_name)),
                              ph.outFile('out_small_%s_m%s%s.stderr' % (fmt, mode, ss_name)),
                              transforms),
                             (ph.inFile('out_small_%s_m%s%s.stdout' % (fmt, mode, ss_name)),
                              ph.outFile('out_small_%s_m%s%s.stdout' % (fmt, mode, ss_name)),
                              transforms),
                             (ph.inFile('out_small_%s_m%s%s.roi' % (fmt, mode, ss_name)),
                              ph.outFile('out_small_%s_m%s%s.roi' % (fmt, mode, ss_name)),
                              transforms),
                             ])
                conf_list.append(conf)
            
    # Execute the tests.
    failures = 0
    for conf in conf_list:
        res = app_tests.runTest(conf)
        # Output to the user.
        print ' '.join(['roi_intersect'] + conf.args),
        if res:
             print 'OK'
        else:
            failures += 1
            print 'FAILED'

    # Cleanup.
    ph.deleteTempDir()

    print '=============================='
    print '     total tests: %d' % len(conf_list)
    print '    failed tests: %d' % failures
    print 'successful tests: %d' % (len(conf_list) - failures)
    print '=============================='
    # Compute and return return code.
    return failures != 0


if __name__ == '__main__':
    sys.exit(app_tests.main(main))
